# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/mainapp.ui',
# licensing of 'ui_files/mainapp.ui' applies.
#
# Created: Wed Oct  2 13:56:17 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 740)
        MainWindow.setMinimumSize(QtCore.QSize(800, 740))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setContentsMargins(6, 2, 6, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.gb_aux_value = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_aux_value.setObjectName("gb_aux_value")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gb_aux_value)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setVerticalSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lb_num_volt = QtWidgets.QLabel(self.gb_aux_value)
        self.lb_num_volt.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(24)
        self.lb_num_volt.setFont(font)
        self.lb_num_volt.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_num_volt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_num_volt.setLineWidth(1)
        self.lb_num_volt.setTextFormat(QtCore.Qt.RichText)
        self.lb_num_volt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_num_volt.setWordWrap(False)
        self.lb_num_volt.setObjectName("lb_num_volt")
        self.gridLayout_8.addWidget(self.lb_num_volt, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gb_aux_value, 0, 6, 1, 1)
        self.gb_main_value = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_main_value.setObjectName("gb_main_value")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gb_main_value)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lb_num_amp = QtWidgets.QLabel(self.gb_main_value)
        self.lb_num_amp.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(24)
        self.lb_num_amp.setFont(font)
        self.lb_num_amp.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_num_amp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_num_amp.setLineWidth(1)
        self.lb_num_amp.setTextFormat(QtCore.Qt.RichText)
        self.lb_num_amp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_num_amp.setWordWrap(False)
        self.lb_num_amp.setObjectName("lb_num_amp")
        self.gridLayout_5.addWidget(self.lb_num_amp, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gb_main_value, 0, 5, 1, 1)
        self.gb_elapsed_time = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_elapsed_time.setMinimumSize(QtCore.QSize(0, 0))
        self.gb_elapsed_time.setObjectName("gb_elapsed_time")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gb_elapsed_time)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lb_num_time = QtWidgets.QLabel(self.gb_elapsed_time)
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(24)
        self.lb_num_time.setFont(font)
        self.lb_num_time.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_num_time.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_num_time.setLineWidth(1)
        self.lb_num_time.setTextFormat(QtCore.Qt.RichText)
        self.lb_num_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_num_time.setWordWrap(False)
        self.lb_num_time.setObjectName("lb_num_time")
        self.gridLayout_6.addWidget(self.lb_num_time, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gb_elapsed_time, 0, 4, 1, 1)
        self.pb_reading = QtWidgets.QProgressBar(self.centralwidget)
        self.pb_reading.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_reading.setMaximum(30)
        self.pb_reading.setProperty("value", 0)
        self.pb_reading.setObjectName("pb_reading")
        self.gridLayout.addWidget(self.pb_reading, 2, 2, 3, 4)
        self.tw_plot_and_data = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_plot_and_data.setObjectName("tw_plot_and_data")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_plot)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fr_main_plot = QtWidgets.QFrame(self.tab_plot)
        self.fr_main_plot.setMinimumSize(QtCore.QSize(450, 0))
        self.fr_main_plot.setAutoFillBackground(False)
        self.fr_main_plot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_main_plot.setLineWidth(1)
        self.fr_main_plot.setObjectName("fr_main_plot")
        self.gridLayout_2.addWidget(self.fr_main_plot, 0, 0, 1, 1)
        self.tw_plot_and_data.addTab(self.tab_plot, "")
        self.gridLayout.addWidget(self.tw_plot_and_data, 1, 1, 1, 6)
        self.pb_run = QtWidgets.QPushButton(self.centralwidget)
        self.pb_run.setMinimumSize(QtCore.QSize(150, 75))
        self.pb_run.setObjectName("pb_run")
        self.gridLayout.addWidget(self.pb_run, 3, 6, 3, 1)
        self.gb_ui_control = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_ui_control.setMaximumSize(QtCore.QSize(400, 16777215))
        self.gb_ui_control.setObjectName("gb_ui_control")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gb_ui_control)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.chk_zero_corr = QtWidgets.QCheckBox(self.gb_ui_control)
        self.chk_zero_corr.setObjectName("chk_zero_corr")
        self.gridLayout_7.addWidget(self.chk_zero_corr, 17, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gb_ui_control)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gb_ui_control)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 22, 0, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.gb_ui_control)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 4, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gb_ui_control)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 27, 0, 1, 4)
        self.cbx_aux_range = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_aux_range.setObjectName("cbx_aux_range")
        self.gridLayout_7.addWidget(self.cbx_aux_range, 25, 1, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.gb_ui_control)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 24, 0, 1, 1)
        self.cbx_aux_port = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_aux_port.setObjectName("cbx_aux_port")
        self.gridLayout_7.addWidget(self.cbx_aux_port, 24, 1, 1, 3)
        self.chk_median = QtWidgets.QCheckBox(self.gb_ui_control)
        self.chk_median.setObjectName("chk_median")
        self.gridLayout_7.addWidget(self.chk_median, 14, 0, 1, 1)
        self.pb_zchk = QtWidgets.QPushButton(self.gb_ui_control)
        self.pb_zchk.setObjectName("pb_zchk")
        self.gridLayout_7.addWidget(self.pb_zchk, 21, 0, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.gb_ui_control)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 25, 0, 1, 1)
        self.cbx_main_port = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_main_port.setObjectName("cbx_main_port")
        self.gridLayout_7.addWidget(self.cbx_main_port, 1, 2, 1, 2)
        self.pte_console = QtWidgets.QPlainTextEdit(self.gb_ui_control)
        self.pte_console.setObjectName("pte_console")
        self.gridLayout_7.addWidget(self.pte_console, 39, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 17, 2, 1, 1)
        self.pb_zero = QtWidgets.QPushButton(self.gb_ui_control)
        self.pb_zero.setObjectName("pb_zero")
        self.gridLayout_7.addWidget(self.pb_zero, 18, 0, 1, 1)
        self.chk_average = QtWidgets.QCheckBox(self.gb_ui_control)
        self.chk_average.setObjectName("chk_average")
        self.gridLayout_7.addWidget(self.chk_average, 9, 0, 4, 1)
        self.cbx_median_rank = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_median_rank.setObjectName("cbx_median_rank")
        self.gridLayout_7.addWidget(self.cbx_median_rank, 14, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gb_ui_control)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 7, 0, 1, 1)
        self.sb_aver_count = QtWidgets.QSpinBox(self.gb_ui_control)
        self.sb_aver_count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_aver_count.setMinimum(1)
        self.sb_aver_count.setMaximum(100)
        self.sb_aver_count.setProperty("value", 10)
        self.sb_aver_count.setObjectName("sb_aver_count")
        self.gridLayout_7.addWidget(self.sb_aver_count, 11, 2, 1, 2)
        self.cbx_aver_class = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_aver_class.setObjectName("cbx_aver_class")
        self.gridLayout_7.addWidget(self.cbx_aver_class, 9, 2, 1, 2)
        self.cbx_aver_type = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_aver_type.setObjectName("cbx_aver_type")
        self.gridLayout_7.addWidget(self.cbx_aver_type, 10, 2, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.gb_ui_control)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 15, 0, 1, 3)
        self.cbx_main_range = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_main_range.setObjectName("cbx_main_range")
        self.gridLayout_7.addWidget(self.cbx_main_range, 4, 2, 1, 2)
        self.cbx_main_speed = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_main_speed.setObjectName("cbx_main_speed")
        self.gridLayout_7.addWidget(self.cbx_main_speed, 7, 2, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.gb_ui_control)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 8, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.gb_ui_control)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 13, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.gb_ui_control)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 26, 0, 1, 1)
        self.cbx_aux_speed = QtWidgets.QComboBox(self.gb_ui_control)
        self.cbx_aux_speed.setObjectName("cbx_aux_speed")
        self.gridLayout_7.addWidget(self.cbx_aux_speed, 26, 1, 1, 3)
        self.lb_num_zero = QtWidgets.QLabel(self.gb_ui_control)
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(16)
        self.lb_num_zero.setFont(font)
        self.lb_num_zero.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_num_zero.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_num_zero.setLineWidth(1)
        self.lb_num_zero.setTextFormat(QtCore.Qt.RichText)
        self.lb_num_zero.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_num_zero.setWordWrap(False)
        self.lb_num_zero.setObjectName("lb_num_zero")
        self.gridLayout_7.addWidget(self.lb_num_zero, 18, 2, 1, 1)
        self.sb_run_time = QtWidgets.QSpinBox(self.gb_ui_control)
        self.sb_run_time.setPrefix("")
        self.sb_run_time.setMinimum(0)
        self.sb_run_time.setMaximum(36000)
        self.sb_run_time.setProperty("value", 30)
        self.sb_run_time.setObjectName("sb_run_time")
        self.gridLayout_7.addWidget(self.sb_run_time, 28, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gb_ui_control)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 28, 0, 1, 1)
        self.gridLayout.addWidget(self.gb_ui_control, 0, 0, 6, 1)
        self.lb_output_file = QtWidgets.QLabel(self.centralwidget)
        self.lb_output_file.setObjectName("lb_output_file")
        self.gridLayout.addWidget(self.lb_output_file, 5, 4, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tw_plot_and_data.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.gb_aux_value.setTitle(QtWidgets.QApplication.translate("MainWindow", "Multimeter (V)", None, -1))
        self.lb_num_volt.setText(QtWidgets.QApplication.translate("MainWindow", "-3.143496E-10", None, -1))
        self.gb_main_value.setTitle(QtWidgets.QApplication.translate("MainWindow", "Picoamperimeter (A)", None, -1))
        self.lb_num_amp.setText(QtWidgets.QApplication.translate("MainWindow", "-3.143496E-10", None, -1))
        self.gb_elapsed_time.setTitle(QtWidgets.QApplication.translate("MainWindow", "Elapsed time (S)", None, -1))
        self.lb_num_time.setText(QtWidgets.QApplication.translate("MainWindow", "-3.143496E-10", None, -1))
        self.pb_reading.setFormat(QtWidgets.QApplication.translate("MainWindow", "%p%", None, -1))
        self.tw_plot_and_data.setTabText(self.tw_plot_and_data.indexOf(self.tab_plot), QtWidgets.QApplication.translate("MainWindow", "Plot", None, -1))
        self.pb_run.setText(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.chk_zero_corr.setText(QtWidgets.QApplication.translate("MainWindow", "Zero Correction", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Picoamperimeter", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Range", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Multimeter", None, -1))
        self.chk_median.setText(QtWidgets.QApplication.translate("MainWindow", "Median ", None, -1))
        self.pb_zchk.setText(QtWidgets.QApplication.translate("MainWindow", "Enable ZCHK", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Range", None, -1))
        self.pb_zero.setText(QtWidgets.QApplication.translate("MainWindow", "Zero", None, -1))
        self.chk_average.setText(QtWidgets.QApplication.translate("MainWindow", "Average Filter", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Speed", None, -1))
        self.sb_aver_count.setSuffix(QtWidgets.QApplication.translate("MainWindow", " Cuentas", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Speed", None, -1))
        self.lb_num_zero.setText(QtWidgets.QApplication.translate("MainWindow", "-3.143496E-10", None, -1))
        self.sb_run_time.setSuffix(QtWidgets.QApplication.translate("MainWindow", " seg", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Duración", None, -1))
        self.lb_output_file.setText(QtWidgets.QApplication.translate("MainWindow", "./data.dat", None, -1))

