# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/mainapp.ui',
# licensing of 'ui_files/mainapp.ui' applies.
#
# Created: Tue Aug  6 16:29:28 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 740)
        MainWindow.setMinimumSize(QtCore.QSize(800, 740))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_save_measure = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save_measure.setMinimumSize(QtCore.QSize(0, 75))
        self.pb_save_measure.setObjectName("pb_save_measure")
        self.gridLayout.addWidget(self.pb_save_measure, 3, 9, 2, 1)
        self.pb_reading = QtWidgets.QProgressBar(self.centralwidget)
        self.pb_reading.setProperty("value", 0)
        self.pb_reading.setObjectName("pb_reading")
        self.gridLayout.addWidget(self.pb_reading, 4, 1, 1, 8)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.lb_progress = QtWidgets.QLabel(self.centralwidget)
        self.lb_progress.setObjectName("lb_progress")
        self.gridLayout.addWidget(self.lb_progress, 3, 2, 1, 7)
        self.gb_main_value = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_main_value.setObjectName("gb_main_value")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gb_main_value)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lcd_main_value = QtWidgets.QLCDNumber(self.gb_main_value)
        self.lcd_main_value.setMinimumSize(QtCore.QSize(150, 75))
        self.lcd_main_value.setSmallDecimalPoint(False)
        self.lcd_main_value.setDigitCount(7)
        self.lcd_main_value.setProperty("value", 0.666666)
        self.lcd_main_value.setObjectName("lcd_main_value")
        self.gridLayout_5.addWidget(self.lcd_main_value, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.gb_main_value, 0, 8, 1, 1)
        self.gb_aux_value = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_aux_value.setObjectName("gb_aux_value")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gb_aux_value)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lcd_aux_value = QtWidgets.QLCDNumber(self.gb_aux_value)
        self.lcd_aux_value.setMinimumSize(QtCore.QSize(150, 75))
        self.lcd_aux_value.setSmallDecimalPoint(False)
        self.lcd_aux_value.setDigitCount(7)
        self.lcd_aux_value.setProperty("value", 0.666666)
        self.lcd_aux_value.setObjectName("lcd_aux_value")
        self.gridLayout_8.addWidget(self.lcd_aux_value, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.gb_aux_value, 0, 9, 1, 1)
        self.tw_plot_and_data = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_plot_and_data.setObjectName("tw_plot_and_data")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_plot)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fr_main_plot = QtWidgets.QFrame(self.tab_plot)
        self.fr_main_plot.setMinimumSize(QtCore.QSize(450, 0))
        self.fr_main_plot.setAutoFillBackground(False)
        self.fr_main_plot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_main_plot.setLineWidth(1)
        self.fr_main_plot.setObjectName("fr_main_plot")
        self.gridLayout_2.addWidget(self.fr_main_plot, 0, 0, 1, 1)
        self.tw_plot_and_data.addTab(self.tab_plot, "")
        self.gridLayout.addWidget(self.tw_plot_and_data, 1, 1, 1, 9)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(360, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_params = QtWidgets.QWidget()
        self.tab_params.setObjectName("tab_params")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_params)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cbx_aver_mode = QtWidgets.QComboBox(self.tab_params)
        self.cbx_aver_mode.setObjectName("cbx_aver_mode")
        self.gridLayout_7.addWidget(self.cbx_aver_mode, 5, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_params)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.pb_run = QtWidgets.QPushButton(self.tab_params)
        self.pb_run.setObjectName("pb_run")
        self.gridLayout_7.addWidget(self.pb_run, 32, 0, 1, 5)
        self.line_4 = QtWidgets.QFrame(self.tab_params)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 13, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.tab_params)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 29, 0, 1, 5)
        self.label_5 = QtWidgets.QLabel(self.tab_params)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 4, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.tab_params)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 16, 0, 1, 5)
        self.cbx_aux_range = QtWidgets.QComboBox(self.tab_params)
        self.cbx_aux_range.setObjectName("cbx_aux_range")
        self.gridLayout_7.addWidget(self.cbx_aux_range, 15, 1, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.tab_params)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 14, 0, 1, 1)
        self.cbx_aux_port = QtWidgets.QComboBox(self.tab_params)
        self.cbx_aux_port.setObjectName("cbx_aux_port")
        self.gridLayout_7.addWidget(self.cbx_aux_port, 14, 1, 1, 4)
        self.cbx_averege_value = QtWidgets.QComboBox(self.tab_params)
        self.cbx_averege_value.setObjectName("cbx_averege_value")
        self.gridLayout_7.addWidget(self.cbx_averege_value, 5, 3, 1, 2)
        self.chk_median = QtWidgets.QCheckBox(self.tab_params)
        self.chk_median.setObjectName("chk_median")
        self.gridLayout_7.addWidget(self.chk_median, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_params)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 7, 0, 1, 1)
        self.pb_zchk = QtWidgets.QPushButton(self.tab_params)
        self.pb_zchk.setObjectName("pb_zchk")
        self.gridLayout_7.addWidget(self.pb_zchk, 12, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.tab_params)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 5, 0, 1, 1)
        self.pb_zero = QtWidgets.QPushButton(self.tab_params)
        self.pb_zero.setObjectName("pb_zero")
        self.gridLayout_7.addWidget(self.pb_zero, 9, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tab_params)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 15, 0, 1, 1)
        self.cbx_main_speed = QtWidgets.QComboBox(self.tab_params)
        self.cbx_main_speed.setObjectName("cbx_main_speed")
        self.gridLayout_7.addWidget(self.cbx_main_speed, 7, 1, 1, 4)
        self.lcd_zero = QtWidgets.QLCDNumber(self.tab_params)
        self.lcd_zero.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_zero.setSmallDecimalPoint(True)
        self.lcd_zero.setDigitCount(7)
        self.lcd_zero.setObjectName("lcd_zero")
        self.gridLayout_7.addWidget(self.lcd_zero, 9, 2, 1, 3)
        self.cbx_main_range = QtWidgets.QComboBox(self.tab_params)
        self.cbx_main_range.setObjectName("cbx_main_range")
        self.gridLayout_7.addWidget(self.cbx_main_range, 4, 1, 1, 4)
        self.cbx_main_port = QtWidgets.QComboBox(self.tab_params)
        self.cbx_main_port.setObjectName("cbx_main_port")
        self.gridLayout_7.addWidget(self.cbx_main_port, 1, 1, 1, 4)
        self.cbx_median_value = QtWidgets.QComboBox(self.tab_params)
        self.cbx_median_value.setObjectName("cbx_median_value")
        self.gridLayout_7.addWidget(self.cbx_median_value, 6, 1, 1, 4)
        self.chk_zero_corr = QtWidgets.QCheckBox(self.tab_params)
        self.chk_zero_corr.setObjectName("chk_zero_corr")
        self.gridLayout_7.addWidget(self.chk_zero_corr, 8, 0, 1, 5)
        self.pte_console = QtWidgets.QPlainTextEdit(self.tab_params)
        self.pte_console.setObjectName("pte_console")
        self.gridLayout_7.addWidget(self.pte_console, 28, 0, 1, 5)
        self.tabWidget.addTab(self.tab_params, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_files = QtWidgets.QWidget()
        self.tab_files.setObjectName("tab_files")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_files)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.le_project_folder = QtWidgets.QLineEdit(self.tab_files)
        self.le_project_folder.setReadOnly(True)
        self.le_project_folder.setClearButtonEnabled(False)
        self.le_project_folder.setObjectName("le_project_folder")
        self.gridLayout_4.addWidget(self.le_project_folder, 0, 0, 1, 1)
        self.tlb_project_folder = QtWidgets.QToolButton(self.tab_files)
        self.tlb_project_folder.setObjectName("tlb_project_folder")
        self.gridLayout_4.addWidget(self.tlb_project_folder, 0, 1, 1, 1)
        self.lw_project_tree = QtWidgets.QListWidget(self.tab_files)
        self.lw_project_tree.setObjectName("lw_project_tree")
        self.gridLayout_4.addWidget(self.lw_project_tree, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_files, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 5, 1)
        self.gb_elapsed_time = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_elapsed_time.setMinimumSize(QtCore.QSize(0, 0))
        self.gb_elapsed_time.setObjectName("gb_elapsed_time")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gb_elapsed_time)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lcd_time = QtWidgets.QLCDNumber(self.gb_elapsed_time)
        self.lcd_time.setSmallDecimalPoint(False)
        self.lcd_time.setDigitCount(4)
        self.lcd_time.setProperty("intValue", 11)
        self.lcd_time.setObjectName("lcd_time")
        self.gridLayout_6.addWidget(self.lcd_time, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gb_elapsed_time, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tw_plot_and_data.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pb_save_measure.setText(QtWidgets.QApplication.translate("MainWindow", "Save Measure", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Progress:", None, -1))
        self.lb_progress.setText(QtWidgets.QApplication.translate("MainWindow", "Reading #", None, -1))
        self.gb_main_value.setTitle(QtWidgets.QApplication.translate("MainWindow", "Picoamperimeter", None, -1))
        self.gb_aux_value.setTitle(QtWidgets.QApplication.translate("MainWindow", "Multimeter", None, -1))
        self.tw_plot_and_data.setTabText(self.tw_plot_and_data.indexOf(self.tab_plot), QtWidgets.QApplication.translate("MainWindow", "Plot", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Picoamperimeter", None, -1))
        self.pb_run.setText(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Range", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Multimeter", None, -1))
        self.chk_median.setText(QtWidgets.QApplication.translate("MainWindow", "Median ", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Speed", None, -1))
        self.pb_zchk.setText(QtWidgets.QApplication.translate("MainWindow", "Enable ZCHK", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Average", None, -1))
        self.pb_zero.setText(QtWidgets.QApplication.translate("MainWindow", "Zero", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Range", None, -1))
        self.chk_zero_corr.setText(QtWidgets.QApplication.translate("MainWindow", "Zero Correction", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_params), QtWidgets.QApplication.translate("MainWindow", "Parameters", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Aux device", None, -1))
        self.tlb_project_folder.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_files), QtWidgets.QApplication.translate("MainWindow", "Files", None, -1))
        self.gb_elapsed_time.setTitle(QtWidgets.QApplication.translate("MainWindow", "Elapsed time", None, -1))

